version: 2


build:
  os: ubuntu-22.04
  tools:
    python: "3.12" # telling readthedocs to use python 3.12, .toml lists the versions actually required for the package
 

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/rtd-requirement.txt
    - method: pip
      path: .